opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - convenience_type
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - prohibited_interface_builder
  - toggle_bool
  - unused_private_declaration
  - unavailable_function
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods